### ISSUE TITLE
TemplateLayoutPathResolver error

### ISSUE THREAD

**Issue by alienlebarge** [alienlebarge/alienlebargech-v3#4]
### Description

When running a `$ npm run dubug` (or `$ DEBUG=* npx eleventy`), I get the following error:

```
Eleventy:EleventyErrorHandler Problem writing Eleventy templates: +0ms
  Eleventy:EleventyErrorHandler TemplateLayoutPathResolver directory does not exist for layouts/bookmark.njk: _includes (Error): +1ms
  Eleventy:EleventyErrorHandler (error stack): Error: TemplateLayoutPathResolver directory does not exist for layouts/bookmark.njk: _includes
  Eleventy:EleventyErrorHandler     at TemplateLayoutPathResolver.findFileName (/Users/cedricaellen/Projects/alienlebargech-v3/node_modules/@11ty/eleventy/src/TemplateLayoutPathResolver.js:96:13)
  Eleventy:EleventyErrorHandler     at TemplateLayoutPathResolver.init (/Users/cedricaellen/Projects/alienlebargech-v3/node_modules/@11ty/eleventy/src/TemplateLayoutPathResolver.js:61:28)
  Eleventy:EleventyErrorHandler     at new TemplateLayoutPathResolver (/Users/cedricaellen/Projects/alienlebargech-v3/node_modules/@11ty/eleventy/src/TemplateLayoutPathResolver.js:15:10)
  Eleventy:EleventyErrorHandler     at new TemplateLayout (/Users/cedricaellen/Projects/alienlebargech-v3/node_modules/@11ty/eleventy/src/TemplateLayout.js:15:24)
  Eleventy:EleventyErrorHandler     at Function.getTemplate (/Users/cedricaellen/Projects/alienlebargech-v3/node_modules/@11ty/eleventy/src/TemplateLayout.js:38:16)
  Eleventy:EleventyErrorHandler     at Template.getData (/Users/cedricaellen/Projects/alienlebargech-v3/node_modules/@11ty/eleventy/src/Template.js:217:37) +0ms
Processed 0 files in 2.54 seconds
```

but when running an standard build `$ eleventy --config lib/eleventy.config.js`, I get no error.

### Ask

I can't find where the problem come from.

#### Things I've tried

1. Change value of `layout` in `src/_content/bookmarks/bookmarks.json`
It change the second line of the error message but can't make it work

**Comment by alienlebarge** [comment]
After +3h trying to find the problem, I finally ask on eleventy's repo.

11ty/eleventy#489

**Comment by alienlebarge** [comment]
> Node version wasn't the same locally than on production.
> Adding `.nvmrc` file with the Node version fixed the problem
> 
> close [11ty/eleventy#489](https://github.com/11ty/eleventy/issues/489)
> close #4
