### ISSUE TITLE
Upgrade to eleventy@1.0.0

### ISSUE THREAD

**Issue by alienlebarge** [alienlebarge/alienlebargech-v3#75]
### Description

Upgrade website to eleventy 1.0.0

### Ask

Make the site work with version 1.0.0

### To Do

- [ ] Upgrade npm package from version 0.12.0 to 1.0.

### Additional Info

...

**Comment by alienlebarge** [comment]
Got a bug when upgrading.

It appears between {{v1.0.0-canary.38}} and {{1.0.0-canary.39}} ([diff](https://github.com/11ty/eleventy/compare/v1.0.0-canary.38...v1.0.0-canary.39)).
It loks like it has something to do with _Deduplicate tags_ https://github.com/11ty/eleventy/commit/d5d110cba92d6abe230b014743df9f75211c4fac#diff-ac754599fcdf5d21057abad8cd6b4f87042811ff9cf98aff931754d10970dce5R591

### log
```
WARN: Eleventy Plugin (@11ty/eleventy-plugin-syntaxhighlight) Compatibility: This project requires the Eleventy version to match '>=0.5.4' but found 1.0.0-canary.39. Use `npm update @11ty/eleventy -g` to upgrade the eleventy global or `npm update @11ty/eleventy --save` to upgrade your local project version.
Problem writing Eleventy templates: (more in DEBUG output)
> boolean false is not iterable (cannot read property Symbol(Symbol.iterator))

`TypeError` was thrown:
    TypeError: boolean false is not iterable (cannot read property Symbol(Symbol.iterator))
        at new Set (<anonymous>)
        at Function.cleanupData (/Users/cedricaellen/Projects/alienlebargech-v3/node_modules/@11ty/eleventy/src/TemplateData.js:591:23)
        at Template.getFrontMatterData (/Users/cedricaellen/Projects/alienlebargech-v3/node_modules/@11ty/eleventy/src/TemplateContent.js:198:25)
        at async Template.getData (/Users/cedricaellen/Projects/alienlebargech-v3/node_modules/@11ty/eleventy/src/Template.js:360:29)
        at async Template.getTemplateMapEntries (/Users/cedricaellen/Projects/alienlebargech-v3/node_modules/@11ty/eleventy/src/Template.js:963:33)
        at async TemplateMap.add (/Users/cedricaellen/Projects/alienlebargech-v3/node_modules/@11ty/eleventy/src/TemplateMap.js:59:21)
        at async Promise.all (index 294)
        at async TemplateWriter._createTemplateMap (/Users/cedricaellen/Projects/alienlebargech-v3/node_modules/@11ty/eleventy/src/TemplateWriter.js:240:5)
        at async TemplateWriter.generateTemplates (/Users/cedricaellen/Projects/alienlebargech-v3/node_modules/@11ty/eleventy/src/TemplateWriter.js:274:5)
        at async TemplateWriter.write (/Users/cedricaellen/Projects/alienlebargech-v3/node_modules/@11ty/eleventy/src/TemplateWriter.js:320:23)
Wrote 0 files in 0.45 seconds (v1.0.0-canary.39)
ERROR: "build:files" exited with 1.
```

**Comment by alienlebarge** [comment]
Problem above seems to come from `tags: false`(https://github.com/11ty/eleventy/pull/1876#issuecomment-890382851)
